from pascal_triangle.pascal_triangle import PyPascalTriangle
from pascal_triangle.cypascal_triangle import (cy_print_pascal_triangle_iterators,
    cy_print_pascal_triangle_non_recursive_even_more_c_like_improved,
    cy_print_pascal_triangle_non_recursive_less_c_like,
    cy_print_pascal_triangle_c_types,
    cy_print_pascal_triangle_non_recursive_even_more_c_like_improved_plus)

from pascal_triangle.cpascal_triangle import (c_print_pascal_triangle, c_print_pascal_triangle_inline_asm)

printer = PyPascalTriangle()
print 'cy_print_pascal_triangle_iterators:'
printer.print_pascal_triangle_testable_fixed_better_naming(5)
print 'cy_print_pascal_triangle_iterators:'
cy_print_pascal_triangle_iterators(5, True)
print 'cy_print_pascal_triangle_non_recursive_even_more_c_like_improved:'
cy_print_pascal_triangle_non_recursive_even_more_c_like_improved(5, True)
print 'cy_print_pascal_triangle_non_recursive_less_c_like:'
cy_print_pascal_triangle_non_recursive_less_c_like(5, True)
print 'cy_print_pascal_triangle_c_types:'
cy_print_pascal_triangle_c_types(5, True)
print 'cy_print_pascal_triangle_non_recursive_even_more_c_like_improved_plus:'
cy_print_pascal_triangle_non_recursive_even_more_c_like_improved_plus(5, True)
print 'c_print_pascal_triangle:'
c_print_pascal_triangle(5, True)
print 'c_print_pascal_triangle_inline_asm:'
c_print_pascal_triangle_inline_asm(5, True)
